# Generated by Django 4.0.4 on 2022-07-05 16:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libraries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('books', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), size=150)),
                ('price_of_books', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
