\
# Generated by Django 4.0.6 on 2022-07-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libraries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('books', models.TextField(blank=True)),
                ('price_of_books', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
